base_url = "https://animaomnium.github.io"
title = "Crash Lime"
description = "Delicious performance 64 bites at a time."
generate_feed = true
compile_sass = false
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "material-dark"
external_links_target_blank = true
external_links_no_follow = true
smart_punctuation = true
