base_url = "https://animaomnium.github.io"
title = "Crash Lime"
description = "Delicious performance 64 bites at a time."
generate_feed = true
compile_sass = false
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "material-dark"
smart_punctuation = true
